### ISSUE TITLE
Re-licencing to GPL-3

### ISSUE THREAD

**Issue by chrisvest** [chrisvest/xv#19]
@gyscos Are you okay with your changes in #16 being re-licensed to GPL-3? There's a crate I'm interested in depending on, but Apache 2.0 programs are not allowed to link GPL licensed libraries.

**Comment by gyscos** [comment]
Sure, I can release that patch as public domain and let you re-license how you prefer.

**Comment by chrisvest** [comment]
I think this acceptance will be enough. Thanks!
