### ISSUE TITLE
Build error installing from crates.io

### ISSUE THREAD

**Issue by tpoliaw** [chrisvest/xv#22]
Trying to install via cargo gives the error
```
error[E0432]: unresolved import `syn::export`
  --> /scratch/usr/cargo/registry/src/github.com-1ecc6299db9ec823/enumset_derive-0.4.4/src/lib.rs:10:10
   |
10 | use syn::export::Span;
   |          ^^^^^^ could not find `export` in `syn`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `enumset_derive`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `xxv v0.1.2`, intermediate artifacts can be found at `/tmp/cargo-installIR0PwI`

Caused by:
  build failed
```

It looks like this was changed in a patch version of `syn` [here](https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759). As xxv doesn't depend on `syn` directly, this might be an issue for one of the other crates but there might be workarounds that can be done from here.

**Comment by chrisvest** [comment]
Yeah, I thought the version fixing in Cargo.lock was supposed to prevent this sort of thing, but apparently not.

I'm not allowed to work on this currently, so you'll have to install from source for the time being.

**Comment by tpoliaw** [comment]
Ok, no worries. Would you take a PR for it or does not allowed include reviewing/merging changes?

**Comment by chrisvest** [comment]
I don't think a PR is necessary – it seems to work when building the current HEAD – but if you submitted one, the most I could do is give you the right to merge it. 🤷‍♂️

**Comment by tpoliaw** [comment]
For anyone else seeing this, installing with the `--locked` flag works.

    cargo install xxv --locked
